### ISSUE TITLE
Crash happening with AFNetworking when using Query.find

### ISSUE THREAD

**Issue by jamneeley** [contentstack/contentstack-ios#15]
We've added ContentStack manually instead of through CocoaPods and have tried to add AFNetworking with both Carthage and SPM. 

Here is the the error: 
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AFHTTPSessionManager GET:parameters:progress:success:failure:]: unrecognized selector sent to instance 0x6000004cc5a0'
terminating with uncaught exception of type NSException
CoreSimulator 776.3 - Device: iOS 14.3/iphone 12 (0D0B7391-FDAA-46FE-A119-FFA39654D4F9) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12
```

**Comment by uttamukkoji** [comment]
Hi @jamneeley,

Thanks for raising the issue.  We will check this on our side and update you once we resolve this issue.

**Comment by uttamukkoji** [comment]
Hi @jamneeley ,

It seems that the link for download SDK in manual installation is pointed to older version, we have updated it to newer version i.e. v3.9.1. Can you please download the latest version from link and check if you are facing issue.

**Comment by jamneeley** [comment]
Thank you! The new link worked
