### ISSUE TITLE
Support For SPM

### ISSUE THREAD

**Issue by ajjumehra** [contentstack/contentstack-ios#18]
As SPM is officially part XCode 13+, Is there any timeline for the same

**Comment by uttamukkoji** [comment]
Hi @ajjumehra ,

Thanks for raising this issue. As we can develop application using Swift language we have introduced [Contentstack-swift](https://github.com/contentstack/contentstack-swift) SDK that you can include through the SPM. 

Please, let us know if this is helpful and works for you.
